services:
  postgres:
    image: postgres
    restart: always
    env_file:
        - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres:/volumes/data
    ports:
      - '5432:5432'
    networks:
      - app-network
  backend:
    container_name: backend
    build: 
     context: ./back
    restart: always
    env_file:
        - .env
    volumes:
      - ./back/src:/src
    ports:
      - '3000:80'
    networks:
      - app-network
  reverse_proxy:
    container_name: reverse_proxy
    build: 
     context: ./nginx
    restart: always
    env_file:
        - .env
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
       - ./front/:/app
    ports:
      - '80:80'
    networks:
      - app-network
  frontend:
    build: 
     context: ./front
    ports:
      - '8000:80'
    networks:
      - app-network
volumes:
  postgres:
   driver: local
  backend:
   driver: local
networks:
  app-network:
   driver: bridge
